GET http://localhost:9000/api/daynotes

###
## Save a Note
POST http://localhost:9000/api/daynotes
Content-Type: application/json

{
  "category": "Mental Health",
  "tag": "Finance",
  "title": "Checked the SimplyWallStreet reports",
  "description": "<b>Checked the SimplyWallStreet reports",
  "date": "2025-05-03",
  "mood": "done"
}
